---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::F77: '1.13'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PGPLOT
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::F77: '1.13'
resources:
  repository: git://github.com/PDLPorters/perl5-PGPLOT.git
version: '2.24'
x_IRC: irc://irc.perl.org/#pdl
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
