.\" @(#)pgperl.1 1.12 90/02/15 SMI; from UCB 4.2
.TH pgperl 1 "28 May 1995"
.SH NAME
pgperl \- a perl interface to PGPLOT

.IX  "pgperl command"  ""  "\fLyes\fP \(em a perl interface to PGPLOT"
.SH DESCRIPTION
.LP
.B pgperl
is a version of the Perl 4.0 language which has been linked
against the PGPLOT fortran library, a very popular package for plotting
astronomical data. (As a glance through any issue of ApJ or MNRAS will
confirm.) The details of this involve some complicated C glue routines
but are transparent to the user. For
further information please consult the WWW online documentation mentioned
below.

.SH SEE ALSO
.LP
perl(1),http://www.ast.cam.ac.uk/~kgb/pgperl.html

